import type { City, Country, ImageData } from '@/apis/countries.types';

const mockImageData: ImageData = {
  id: 1,
  bucket: "nestjsstorage",
  objectKey: "uploads/1753030967855-icon.webp",
  mime: "image/webp",
  size: 20076,
  scope: "PUBLIC",
  ownerId: null,
  encrypted: false,
  uploadedAt: "2025-07-20T17:02:48.269Z",
  deletedAt: null,
};

const mockCityData: City = {
  id: 1,
  countryId: 1,
  name: "New York",
  slug: "new-york",
  description: "The Big Apple - a vibrant metropolis",
  center: [-74.006, 40.7128],
  radius: "15.00",
  avgMealPrice: "25.00",
  isActive: true,
  avgRating: "4.5",
  ratingCount: 1250,
  createdAt: "2025-07-20T22:18:12.159Z",
  updatedAt: "2025-07-23T17:55:18.019Z",
  deletedAt: null,
  mainImage: mockImageData,
  galleryImages: [mockImageData],
};

export const mockCountries: Country[] = [
  {
    id: 1,
    name: 'United States',
    code: 'US',
    currency: 'USD',
    timezone: 'America/New_York',
    description: 'The United States is a vast country with diverse landscapes, from the skyscrapers of New York to the beaches of California.',
    is_active: true,
    avgRating: '4.5',
    ratingCount: 1250,
    createdAt: '2025-07-20T22:18:12.159Z',
    updatedAt: '2025-07-23T17:55:18.019Z',
    deletedAt: null,
    mainImage: mockImageData,
    galleryImages: [mockImageData],
    cities: [mockCityData],
  },
  {
    id: 2,
    name: 'Canada',
    code: 'CA',
    currency: 'CAD',
    timezone: 'America/Toronto',
    description: 'Canada is known for its stunning natural beauty, from the Rocky Mountains to the Northern Lights.',
    is_active: true,
    avgRating: '4.3',
    ratingCount: 890,
    createdAt: '2025-07-20T22:18:12.159Z',
    updatedAt: '2025-07-23T17:55:18.019Z',
    deletedAt: null,
    mainImage: mockImageData,
    galleryImages: [mockImageData],
    cities: [],
  },
  {
    id: 3,
    name: 'United Kingdom',
    code: 'GB',
    currency: 'GBP',
    timezone: 'Europe/London',
    description: 'The UK is rich in history and culture, from the ancient castles of Scotland to the modern city of London.',
    is_active: true,
    avgRating: '4.4',
    ratingCount: 1100,
    createdAt: '2025-07-20T22:18:12.159Z',
    updatedAt: '2025-07-23T17:55:18.019Z',
    deletedAt: null,
    mainImage: mockImageData,
    galleryImages: [mockImageData],
    cities: [],
  },
  {
    id: 4,
    name: 'France',
    code: 'FR',
    currency: 'EUR',
    timezone: 'Europe/Paris',
    description: 'France is famous for its art, fashion, gastronomy, and architecture, particularly the Eiffel Tower.',
    is_active: true,
    avgRating: '4.6',
    ratingCount: 1350,
    createdAt: '2025-07-20T22:18:12.159Z',
    updatedAt: '2025-07-23T17:55:18.019Z',
    deletedAt: null,
    mainImage: mockImageData,
    galleryImages: [mockImageData],
    cities: [],
  },
  {
    id: 5,
    name: 'Germany',
    code: 'DE',
    currency: 'EUR',
    timezone: 'Europe/Berlin',
    description: 'Germany is known for its engineering, beer, and rich cultural heritage.',
    is_active: true,
    avgRating: '4.2',
    ratingCount: 950,
    createdAt: '2025-07-20T22:18:12.159Z',
    updatedAt: '2025-07-23T17:55:18.019Z',
    deletedAt: null,
    mainImage: mockImageData,
    galleryImages: [mockImageData],
    cities: [],
  },
  {
    id: 6,
    name: 'Japan',
    code: 'JP',
    currency: 'JPY',
    timezone: 'Asia/Tokyo',
    description: 'Japan is a fascinating blend of ancient traditions and cutting-edge technology.',
    is_active: true,
    avgRating: '4.7',
    ratingCount: 1500,
    createdAt: '2025-07-20T22:18:12.159Z',
    updatedAt: '2025-07-23T17:55:18.019Z',
    deletedAt: null,
    mainImage: mockImageData,
    galleryImages: [mockImageData],
    cities: [],
  },
  {
    id: 7,
    name: 'Australia',
    code: 'AU',
    currency: 'AUD',
    timezone: 'Australia/Sydney',
    description: 'Australia is known for its unique wildlife, beautiful beaches, and the iconic Sydney Opera House.',
    is_active: true,
    avgRating: '4.4',
    ratingCount: 1200,
    createdAt: '2025-07-20T22:18:12.159Z',
    updatedAt: '2025-07-23T17:55:18.019Z',
    deletedAt: null,
    mainImage: mockImageData,
    galleryImages: [mockImageData],
    cities: [],
  },
  {
    id: 8,
    name: 'Brazil',
    code: 'BR',
    currency: 'BRL',
    timezone: 'America/Sao_Paulo',
    description: 'Brazil is famous for its Carnival, Amazon rainforest, and beautiful beaches.',
    is_active: true,
    avgRating: '4.1',
    ratingCount: 800,
    createdAt: '2025-07-20T22:18:12.159Z',
    updatedAt: '2025-07-23T17:55:18.019Z',
    deletedAt: null,
    mainImage: mockImageData,
    galleryImages: [mockImageData],
    cities: [],
  },
  {
    id: 9,
    name: 'India',
    code: 'IN',
    currency: 'INR',
    timezone: 'Asia/Kolkata',
    description: 'India is a diverse country with rich culture, history, and the iconic Taj Mahal.',
    is_active: true,
    avgRating: '4.3',
    ratingCount: 1100,
    createdAt: '2025-07-20T22:18:12.159Z',
    updatedAt: '2025-07-23T17:55:18.019Z',
    deletedAt: null,
    mainImage: mockImageData,
    galleryImages: [mockImageData],
    cities: [],
  },
  {
    id: 10,
    name: 'South Africa',
    code: 'ZA',
    currency: 'ZAR',
    timezone: 'Africa/Johannesburg',
    description: 'South Africa is known for its wildlife, beautiful landscapes, and rich cultural diversity.',
    is_active: true,
    avgRating: '4.0',
    ratingCount: 750,
    createdAt: '2025-07-20T22:18:12.159Z',
    updatedAt: '2025-07-23T17:55:18.019Z',
    deletedAt: null,
    mainImage: mockImageData,
    galleryImages: [mockImageData],
    cities: [],
  },
];

export const mockCountriesResponse = {
  data: mockCountries,
  totalCount: mockCountries.length.toString(),
  page: 1,
  limit: 20,
  totalPages: 1,
  orderBy: 'createdAt',
  orderDir: 'desc',
}; 